import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#1a1c1c",
        "on-secondary-container": "#785a1a",
        "surface-bright": "#f8f9ff",
        background: "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#5f5e5e",
        "tertiary-fixed": "#e2e2e2",
        secondary: "#775a19",
        "tertiary-container": "#1a1c1c",
        "on-primary-fixed-variant": "#474746",
        "secondary-container": "#fed488",
        "on-background": "#0b1c30",
        surface: "#f8f9ff",
        "inverse-primary": "#c8c6c5",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#5d4201",
        "surface-container-highest": "#d3e4fe",
        "outline-variant": "#c4c7c7",
        "secondary-fixed": "#ffdea5",
        "primary-fixed": "#e5e2e1",
        "on-tertiary": "#ffffff",
        tertiary: "#000000",
        "tertiary-fixed-dim": "#c6c6c7",
        "primary-fixed-dim": "#c8c6c5",
        primary: "#000000",
        "surface-dim": "#cbdbf5",
        "primary-container": "#1c1b1b",
        "on-surface": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "on-error": "#ffffff",
        "on-tertiary-container": "#838484",
        "surface-container-high": "#dce9ff",
        "surface-variant": "#d3e4fe",
        "on-secondary": "#ffffff",
        "surface-container": "#e5eeff",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#444748",
        "error-container": "#ffdad6",
        outline: "#747878",
        "on-primary-fixed": "#1c1b1b",
        "on-secondary-fixed": "#261900",
        "on-tertiary-fixed-variant": "#454747",
        "secondary-fixed-dim": "#e9c176",
        "on-error-container": "#93000a",
        "inverse-surface": "#213145",
        "on-primary-container": "#858383",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "32px",
        "glass-padding": "24px",
        unit: "8px",
        "container-padding": "64px",
        "mobile-margin": "20px",
      },
      fontFamily: {
        "body-md": ["'Hanken Grotesk'", "sans-serif"],
        "label-md": ["'Hanken Grotesk'", "sans-serif"],
        "body-lg": ["'Hanken Grotesk'", "sans-serif"],
        "headline-md": ["'Manrope'", "sans-serif"],
        "headline-lg-mobile": ["'Manrope'", "sans-serif"],
        "display-lg": ["'Manrope'", "sans-serif"],
        "headline-lg": ["'Manrope'", "sans-serif"],
        hanken: ["'Hanken Grotesk'", "sans-serif"],
        manrope: ["'Manrope'", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "300" },
        ],
        "display-lg": [
          "64px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "200",
          },
        ],
        "headline-lg": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "300" },
        ],
      },
      keyframes: {
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        pulse: "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in-up": "fadeInUp 0.7s ease forwards",
      },
    },
  },
  plugins: [],
};

export default config;
